ministryofjustice/opg-data-lpa-instructions-preferences

.pre-commit-config.yaml, lambdas/image_processor/app/handler.py, lambdas/image_request_handler/app/handler.py
=> add pre-commit hooks

.github/workflows/sub-task-docker-build.yml, .github/workflows/workflow-path-to-live.yml, .github/workflows/workflow-pull-request.yml, README.md, integration/test_end_to_end.py, lambdas/image_processor/app/handler.py, lambdas/image_processor/tests/handler_test.py, mock-services/sirius/app/sirius-local.yml, mock-services/sirius/app/sirius.yml, scripts/post-request.py, scripts/wipe-images-s3.py, terraform/environment/lambda.tf, terraform/environment/mock_sirius.tf
prerequisites for UAT testing
Fixes UML-2771
Set up some dummy cases on sirius integration and made readme notes and helper script for using them. 
This PR also enables production env.
NA
=> UML-2771 prerequisites for UAT testing

integration/test_end_to_end.py
=> extend wait time

integration/config.py, integration/test_end_to_end.py, lambdas/image_request_handler/app/handler.py, lambdas/image_request_handler/tests/handler_test.py
Change the response from the Lambda function to be camelCase instead of snake_cake.
Fixes UML-2914
Change the response and tests.
=> UML-2914 Change response to be camelCase

integration/requirements.txt
Add pytest-order to requirements.txt
Fixes UML-2915
=> UML-2915 Add pytest-order to requirements.txt

integration/test_end_to_end.py, terraform/environment/lambda.tf
Increase the memory of Image Processor Lambda function to avoid OOM issues.
Fixes UML-2926
=> UML-2926 Increase memory of Image Processor Lambda function

lambdas/image_processor/app/handler.py, lambdas/image_processor/app/utility/custom_logging.py, lambdas/image_processor/app/utility/extraction_service.py, lambdas/image_processor/extraction/metadata/hw114.json, lambdas/image_processor/extraction/metadata/lp1f.json, lambdas/image_processor/extraction/metadata/lp1f_lp.json, lambdas/image_processor/extraction/metadata/lp1h.json, lambdas/image_processor/extraction/metadata/lp1h_lp.json, lambdas/image_processor/extraction/metadata/lpa_pa.json, lambdas/image_processor/extraction/metadata/lpa_pw.json, lambdas/image_processor/extraction/metadata/lpc.json, lambdas/image_processor/extraction/metadata/lpc_as_part_of_scan.json, lambdas/image_processor/extraction/metadata/lpc_lp.json, lambdas/image_processor/extraction/metadata/pfa117.json, lambdas/image_processor/extraction/metadata/pfa_c.json, lambdas/image_processor/requirements.txt, lambdas/image_processor/tests/utility/extraction_service_test.py
Some improvements
Fixes UML-2926
- Stack trace in one message (hopefully)
- Main error logged as ERROR log level 
- Check if file type is pdf and skip if not
- Update bounding boxes to be 5 pixels more each side
- Request ID added
NA
=> UML-2926 some further fixes from pre uat testing

scripts/post-request.py
Add parameters to the post-request.py script
Fixes UML-2932
=> UML-2932 Add parameters to post-request.py script

lambdas/image_processor/app/utility/extraction_service.py, terraform/environment/log_metrics.tf
Create Log Metric for page count / file size of PDFs processed
Fixes UML-2925
=> UML-2925 Metrics for PDF page count / file size

.github/workflows/delete_specific_lpa.yml
Correct the role assumed by delete LPA workflow
Fixes UML-3045
=> UML-3045 Correct LPA delete role

lambdas/image_processor/Dockerfile, lambdas/image_processor/Dockerfile-tests, lambdas/image_processor/requirements.txt, lambdas/image_request_handler/Dockerfile, lambdas/image_request_handler/Dockerfile-tests, lambdas/image_request_handler/requirements.txt
Upgrade Lambda functions to Python 3.12
Fixes UML-3192
Upgrade base containers to Python 3.12. Upgrade form-tools to 0.1.5 to support Python 3.12.
=> UML-3192 Upgrade to Python 3.12

local-services/localstack-processor/Dockerfile, local-services/localstack-request-handler/Dockerfile, mock-services/sirius/app/Dockerfile
=> Renovate Update minor and patch updates (Docker)

renovate.json
Support the non-standard nginx image name in Renovate
Fixes UML-3196
=> UML-3196 Renovate support non-std nginx image name

mock-services/sirius/web/Dockerfile
=> Upgrade OpenSSL in nginx web

docs/runbooks/delete-an-lpa-scan.md
Add a runbook with information on how to delete distorted extracts
Fixes UML-3099
=> UML-3099 Add runbook for deleting distorted images

terraform/environment/terraform.tfvars.json
Correct the extra role ARN.
Fixes #89 
=> UML-3216 Correct extra role ARN

.github/workflows/sub-task-terraform.yml, .github/workflows/workflow-path-to-live.yml, .github/workflows/workflow-pull-request.yml, .pre-commit-config.yaml, terraform/account/kms.tf, terraform/environment/.envrc, terraform/environment/kms.tf, terraform/environment/log_metrics.tf, terraform/environment/pagerduty.tf, terraform/environment/terraform.tf, terraform/environment/terraform.tfvars.json, terraform/environment/variables.tf, terraform/environment/versions.tf
Add PagerDuty alerting for Errors generated in I&P
Fixes UML-2763
Create SNS topics and a subscription to send alerts to PagerDuty.
=> UML-2763 Add PagerDuty alerts for errors

.github/workflows/scheduled_destroy.yml
Add a missing Pagerduty token for destroy
Fixes UML-2763
=> UML-2763: Add missing PagerDuty token for destroy

terraform/environment/versions.tf
=> UML-2763 Remove unneeded PD provider

.github/workflows/workflow-path-to-live.yml
=> UML-2763 Fix broken pipeline

terraform/account/terraform.tfvars.json
=> UML-2763 Switch PD Service IDs around

terraform/environment/terraform.tfvars.json
Fix the permissions to allow UAL and Sirius operator roles to execute-api on the API Gateway
Fixes UML-3216
=> UML-3216 Add UAL operator execute-api permissions

lambdas/image_request_handler/tests/handler_test.py
_fix mock_aws decorators to fix build_
_update decorators._
=> fix mock_aws decorators

integration/test_end_to_end.py
=> UML-3323 Empty entire development S3 bucket on end2end test

lambdas/image_processor/app/handler.py, lambdas/image_request_handler/app/handler.py
_if xray fails, continue without breaking. This mainly affects local running but theoretically could affect prod._
_fix python files._
=> if xray fails, continue without breaking

.github/workflows/sub-task-lint.yml
_remove duplication to fix broken builds_
_removed code block_
=> UML 3429 Remove tfsec pr commentor from I&P workflow

scripts/README.md, scripts/post-request.py, scripts/requirements.txt
Shows error from Sirius in the terminal, giving clarity for the user.
Fixes UML-3451
=> UML-3451: show collection error in terminal

scripts/post-request.py
Stops json parse error
Fixes UML-3458
=> UML-3458: mods

lambdas/image_request_handler/Dockerfile, mock-services/sirius/app/Dockerfile, mock-services/sirius/web/Dockerfile
=> UML-3502: Upgrade mock sirius dependencies

lambdas/image_processor/Dockerfile, lambdas/image_processor/Dockerfile-tests, lambdas/image_request_handler/Dockerfile, lambdas/image_request_handler/Dockerfile-tests
Update python image and expat package
Fixes uml-3615
=> Uml 3615 crit vulns

.github/workflows/sub-task-docker-build.yml
Adds rate limit fix for Trivy
Fixes UML-3653
=> Add rate limti fix

.github/workflows/sub-task-integration-tests.yml
Fixes python env error
Fixes UML-3673
=> Update intergration test python

.github/workflows/sub-task-docker-build.yml
Adds ava db to trivy job
Fixes UML-3653
=> Adding java db to trivy job

terraform/environment/iam.tf
=> SP-2525 - Allow KMS Decrypt for Secrets Manager CMKMS Key #minor

.github/workflows/delete_specific_lpa.yml, .github/workflows/scheduled_destroy.yml, .github/workflows/sub-task-docker-build.yml, .github/workflows/sub-task-integration-tests.yml, .github/workflows/sub-task-lint.yml, .github/workflows/sub-task-tags.yml, .github/workflows/sub-task-terraform.yml, .github/workflows/sub-task-unit-tests.yml, .github/workflows/workflow-pull-request.yml, renovate.json
Pins GitHub actions to a specific commit hash, rather than version
=> update dependencies with commit hash

docs/runbooks/reextract-an-lpa-scan.md
=> update scan re-extraction documentation

mock-services/sirius/app/Dockerfile
=> Update version of Cross Spawn

terraform/environment/scripts/workspace_cleanup.sh
So it doesn't get automatically deleted #patch
=> Add "demo" to protected workspaces
