ministryofjustice/opg-data-lpa-instructions-preferences

- terraform/environment/sqs.tf
Prevent SQS messages being deleted when the Lambda function timesout
Fixes UML-2926
> UML-2926 Don't delete SQS messages early

- lambdas/image_processor/app/utility/extraction_service.py
- terraform/environment/lambda.tf
- terraform/environment/modules/lambda/main.tf
- terraform/environment/modules/lambda/variables.tf
Images are currently stored in-memory instead of on-disk when being processed. This is leading to OOM errors in Lambda for documents with a lot of pages. Increase the ephemeral storage from 512MB to 10GB and places the images in the /tmp directory.
Fixes UML-2926
> UML-2926 Store images on-disk instead of in-memory

- lambdas/image_request_handler/app/handler.py
- lambdas/image_request_handler/tests/handler_test.py
_A collection error should result in a 200 from the lambda not a 500._
_change the return code_
> COLLECTION_ERROR needs to result in a 200 rather than a 500 response

- terraform/environment/api_rest.tf
Remove deprecated template_file to allow terraform commands to be run locally
Fixes UML-2940
> UML-2940 Remove use of template_file resource in TF

- lambdas/image_processor/app/utility/extraction_service.py
- lambdas/image_processor/tests/handler_test.py
- lambdas/image_processor/tests/utility/extraction_service_test.py
Pick up C sheets where template is not set by sirius
Fixes UML-2942
Where we have a match, find out what the template is and filter the store to that cont sheet template.
NA
> UML-2942 add continuation sheet support for non template sheets

- lambdas/image_processor/app/utility/extraction_service.py
Resolve the issue where the image processing Lambda won't work for cases which have non-PDF files attached and also require OCR scanning.
Fixes UML-2955
Add an is_pdf_file check before OCR scan.
> UML-2955: Check if file is PDF before OCR scanning

- lambdas/image_processor/app/utility/extraction_service.py
Resolve issues where barcode scans and OCR matching fail on legible PDFs.
Fixes UML-2960
Flip the images up to 3 times to check whether the barcode is in a different location.
> UML-2960 Fix barcode scanning issues

- lambdas/image_processor/app/utility/extraction_service.py
Resolve the 'NoneType' object has no attribute 'image_page_map' error that affects a small amount of LPAs.
Fixes UML-2957
Perform OCR matching if only continuation sheets are found
> UML-2957 OCR match if only continuation barcodes found

- docs/runbooks/common-reporting.md
- terraform/account/log_insights.tf
These queries are used for reporting, such as failure percentage and tracking which failed and why
> Add saved queries for log insights

- .github/workflows/sub-task-unit-tests.yml
- lambdas/image_processor/app/handler.py
- lambdas/image_processor/app/utility/extraction_service.py
- lambdas/image_processor/app/utility/image_reader.py
- lambdas/image_processor/app/utility/ocr.py
- lambdas/image_processor/tests/utility/extraction_service_test.py
- terraform/environment/lambda.tf
Reduce memory usage of Lambda function
Fixes UML-2937
Reduce the amount of images residing in memory on the image processor to prevent OOM killer from pre-maturing ending the Lambda function.
Save images to disk and load to memory as and when needed rather than keeping in memory.
N/A
> UML-2937 Reduce images in memory in image processor

- .github/workflows/sub-task-docker-build.yml
- .github/workflows/workflow-path-to-live.yml
Don't expire production images
Fixes UML-2985
Prefix images made during Path to Live with `main` so that they don't expire.
> UML-2985 Prefix production image tag with main

- lambdas/image_processor/app/utility/extraction_service.py
- lambdas/image_processor/requirements-tests.txt
- lambdas/image_processor/requirements.txt
Only rotate images when confidence is high that it's not aligned properly and the script has been detected as Latin.
Fixes UML-2973
Use imutil to rotate the image if Tesseract returns a high confidence level that the image isn't facing the right direction
> LPAL-2973 Only rotate images when confident wrong

- integration/config.py
Fix the config.py for tests.
Fixes UML-3091
Currently, iap-700000000096-instructions and iap-700000000097-instructions aren't in the config.py resulting in them never being deleted. This causes these LPAs causes them to be always stuck in COLLECTION_COMPLETE for subsequent integration test runs.
> UML-3091 Fix config.py for tests

- renovate.json
We have some python version dependent files so bundling docker updates that bring in python version 3.12 docker files causes issues.
> Split out dockerfile updates in renovate to avoid python issues

- .github/workflows/sub-task-integration-tests.yml
- integration/config.py
- integration/test_end_to_end.py
- lambdas/image_processor/app/utility/path_selection_service.py
- lambdas/image_processor/tests/utility/path_selection_service_test.py
- mock-services/sirius/app/sirius-local.yml
- mock-services/sirius/app/sirius.yml
- mock-services/sirius/web/nginx-local.conf
- mock-services/sirius/web/nginx.conf
_This is a bug fix. Currently, its possible for a LPA to have the boxes checked to indicate there are further instructions and/or preferences on continuation sheet(s), but in a minority of cases the system may fail to read these sheets, and not make the user aware. This change takes us to COLLECTION_ERROR if this happens, so a user doesn't get the false impression they have all the instructions and preferences they need, when there's extra info on continuation sheets which we failed to load an image for._
_Extra logic in the image processor. Added continuation sheets for lpa0047 in mock , as this would now error out otherwise. Added lpa0098 which should error out due to lack of continuation sheets. Modified tests to also test for collection_error_
> UML-3199 go to COLLECTION_ERROR if we fail to scan continuation sheets we were expecting

- terraform/environment/terraform.tfvars.json
Allow execute-api:Invoke for operator role to allow operators to rerun an image scan.
Fixes UML-3216
> UML-3216: Allow execute-api for operator

- terraform/account/kms.tf
- terraform/account/pagerduty.tf
Allow CloudWatch to publish to the alarm SNS topic so that alarms can be send to PagerDuty
Fixes UML-2763
> UML-2763 Allow CloudWatch to publish to alarm SNS topic

- renovate.json
_Renovate is currently creating PRs in parallel. These tend to trample on each other with terraform locks, especially when they auto-rebuild when main gets updated. For now we should only allow 1 at a time until we have a better way._
_Update renovate config._
> reduce concurrent renovate PRs

- scripts/post-request.py
This makes the script retry multiple times until we either get `COLLECTION_COMPLETE` or `COLLECTION_ERROR`. This prevents the user needing guess timing and  do multiple retries 
Fixes UML-3458
> UML-3458: automatically retry until data returned

- mock-services/sirius/app/Dockerfile
Use version included in stoplight/prism image (currently 10.8.2)
> Stop downgrading npm

- .github/workflows/workflow-path-to-live.yml
- terraform/environment/.envrc
- terraform/environment/iam.tf
- terraform/environment/lambda.tf
- terraform/environment/mock_sirius.tf
- terraform/environment/terraform.tfvars.json
- terraform/environment/variables.tf
Set up configuration and add deployment step to pipeline
Fixes SP-2853 #patch
I've taken the same approach as [opg-data-lpa](https://github.com/ministryofjustice/opg-data-lpa/pull/230), to separate the environment mapping from the account configuration. This allows us to have multiple envs in the same account.
> Add demo environment

- .github/workflows/workflow-path-to-live.yml
We need to mark `create_tags` as a dependency step so that we can pass the version_tag to Terraform.
For SP-2853 #patch
> Fix demo deployment config
